### ISSUE TITLE
DOC: Addition of Contributor's logo's

### ISSUE THREAD

**Issue by Anjaliavv51** [SaiyamTuteja/Faculty_Evaluation_System#62] opened 2024-06-01 10:57 UTC
### What's wrong with the existing documentation

Ntg , addition of Contributor's logo's.

### Add ScreenShots

![image](https://github.com/SaiyamTuteja/Faculty_Evaluation_System/assets/154777864/fefd3fa0-11dd-4d23-bb25-e3c1cd22ce2f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by aswinikalyan30** [comment] 2024-06-01 11:34
Duplicate of #59

**Closed by aswinikalyan30** 2024-06-01 11:34 UTC
