### ISSUE TITLE
DOC: Adding All Contributors Profile Photos in Readme.md file

### ISSUE THREAD

**Issue by say-het** [SaiyamTuteja/Faculty_Evaluation_System#61] opened 2024-06-01 07:25 UTC
### What's wrong with the existing documentation

 - It lacks Contributors Profiles in Readme.md
 - It should be Like the image that I have shared

Hey! @aswinikalyan30 I have already fixed it. Can you assign me this issue under GSSoC so that I can raise a PR.

Little about me: I am an experienced contributor as I have successfully completed Hacktoberfest-2020 and Hacktoberfest-2023

### Add ScreenShots

![image](https://github.com/SaiyamTuteja/Faculty_Evaluation_System/assets/71073587/86191e5a-3054-4359-a127-47d996f8d246)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by aswinikalyan30** [comment] 2024-06-01 08:03
Hey @say-het that's not how GSSoc contribution works . You get assigned the issue and then work on it. This is a duplicate of #59 and someone's already working on it.

**Closed** 2024-06-01 08:03 UTC

**Comment by say-het** [comment] 2024-06-01 08:36
Oh ok but you have not assigned #59. It says "No one assigned" on it.

**Comment by aswinikalyan30** [comment] 2024-06-01 11:37
You can open any other issue
