### ISSUE TITLE
Feat: Workflow for closing old issues

### ISSUE THREAD

**Issue by Asymtode712** [SaiyamTuteja/Faculty_Evaluation_System#42] opened 2024-05-20 21:48 UTC
### Describe the feature

This feature aims to automate the process of managing old issues, ensuring that the repository remains organized and focused on relevant tasks. By automatically closing old issues, it reduces manual overhead for repository maintainers and helps keep the issue tracker tidy and up-to-date.

### Add ScreenShots

![Close Old Iss](https://github.com/SaiyamTuteja/Faculty_Evaluation_System/assets/115717746/f1b1d4ee-b533-4e08-b27a-d8606d489e8a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Asymtode712** [comment] 2024-05-20 21:49
@aswinikalyan30 please assign me this issue under gssoc'24

**Comment by aswinikalyan30** [comment] 2024-05-21 02:01
What's the criteria on which you decide the issue is old and to be closed?

**Comment by Asymtode712** [comment] 2024-05-21 04:04
> What's the criteria on which you decide the issue is old and to be closed?

If there's no activity on the issue like no comments are made within a span of 30 days then it would be closed

**Comment by aswinikalyan30** [comment] 2024-05-22 13:17
Sure. Assigned to you

**Closed** 2024-05-23 14:12 UTC
Labels: gssoc, level1
