### ISSUE TITLE
Feat:cForgot Passowrd in login page 

### ISSUE THREAD

**Issue by sk-upadhyay** [SaiyamTuteja/Faculty_Evaluation_System#72] opened 2024-06-06 02:42 UTC
### Describe the feature

Use the signup details for forgotten password for changing the password 

### Add ScreenShots

![image](https://github.com/SaiyamTuteja/Faculty_Evaluation_System/assets/66321059/d6b37e33-f0b6-4e59-93f7-e47823b9e62f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by aswinikalyan30** [comment] 2024-06-06 03:20
Looks like a duplicate of #52 , can you pull the latest changes and check?

**Closed** 2024-06-06 05:06 UTC
